### ISSUE TITLE
After updating method to fetch browser version from excel sheet Firefox is not running locally with the provided version

### ISSUE THREAD

**Issue by maxsudik** [maxsudik/JQMax#78]

**Comment by maxsudik** [comment]
This is the commit where it was working latest - b05b52e69143e9db72f7aaa7cdeaa9d385d7fad9
`ERROR StatusLogger Log4j2 could not find a logging implementation. Please add log4j-core to the classpath. Using SimpleLogger to log to the console...
[{testdescription=To check whether the user can successfully login and logout, count=1, testname=loginTest, priority=1, execute=no}, {testdescription=To check whether this test is executed, count=1, testname=newTest, priority=1, execute=no}, {testdescription=To check import of data from excel, count=1, testname=loginTestUsingExcelData, priority=1, execute=yes}, {testdescription=To check import of data from excel, count=1, testname=newTestUsingExcelData, priority=1, execute=no}]
[{fname=Max, password=admin123, browser=chrome, testname=loginTestUsingExcelData, execute=no, version=N/A, username=Admin}, {fname=N/A, password=N/A, browser=N/A, testname=loginTestUsingExcelData, execute=no, version=N/A, username=N/A}, {fname=Bob, password=admin123, browser=firefox, testname=loginTestUsingExcelData, execute=yes, version=95.0.2, username=Admin}, {fname=N/A, password=N/A, browser=N/A, testname=newTestUsingExcelData, execute=no, version=N/A, username=N/A}, {fname=John, password=admin123, browser=firefox, testname=newTestUsingExcelData, execute=no, version=N/A, username=Admin}, {fname=N/A, password=N/A, browser=N/A, testname=newTestUsingExcelData, execute=no, version=N/A, username=N/A}]

java.lang.NullPointerException
	at driver.Driver.initializeDriver(Driver.java:25)
	at tests.BaseTest.setUp(BaseTest.java:17)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
	at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
	at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
	at org.testng.internal.TestInvoker.runConfigMethods(TestInvoker.java:700)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:527)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)`
